default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000
  username: postgres
  password: 1
  host: localhost

development:
  <<: *default
  database: hello_rails

test:
  <<: *default
  database: hello_rails_test
  
production:
  <<: *default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000
  username: budget_app_bjvy_user
  password: <%= ENV['DATABASE_PASSWORD'] %>
  host:  dpg-cm06e6ta73kc73c13410-a
  port: 5432
  database: <%= ENV['DATABASE_NAME'] %>